int read_keypad(void);
int read_delay(void);
void display_output(int);


int main()
{
	int keypad;
	int delay;

	//initialize with hypen (-)
	display_output(1);
	//1st read after power startup
	delay = read_delay();
	keypad = 0;

	while(1)
	{
		/*Keypad read only delay is High*/
		if(delay) keypad = read_keypad();

		if(keypad == 0) display_output(1);
		else display_output(keypad);

		// Delay to avoid key Debounce
    	delay = read_delay();
	}	
	return(0);
}

int read_keypad(void)
{
	const int rowcode[5]={14,13,11,7,0};
	int keypad, row;
	int i=0;
	int mask=0xFFFFFFF0;

	while(rowcode[i] > 0)
	{
		row = rowcode[i];

		asm volatile(
			"and x30,x30,%1\n\t"
	    	"or x30, x30,%0\n\t"
	    	:
	    	:"r"(row),"r"(mask)
	    	:"x30"
	    	);
	    	
	    asm volatile(
	    	"andi %0, x30, 240\n\t"
	    	:"=r"(keypad)
	    	:
	    	:
	    	);
	    if(keypad != 240)
	    {
	    	// pressed key is scaned in this row
			break;
		}
		i++;		
	}

	if(row == 0)//no button pressed
	{
		//no button pressed yet
		return 0;
	}
	else
	{
		if(row == 14)//row0, b1110
		{
			if(keypad == 224)      keypad=48; //1
			else if(keypad == 208) keypad=109;//2
			else if(keypad == 176) keypad=121;//3
			else if(keypad == 112) keypad=119;//A
		}
		else if(row == 13)//row1
		{
			if(keypad == 224)      keypad=51;//4
			else if(keypad == 208) keypad=91;//5
			else if(keypad == 176) keypad=94;//6
			else if(keypad == 112) keypad=31;//b
		}
		else if(row == 11)//row2
		{
			if(keypad == 224)      keypad=112;//7
			else if(keypad == 208) keypad=127;//8
			else if(keypad == 176) keypad=115;//9
			else if(keypad == 112) keypad=78; //C
		}
		else if(row == 7)//row3
		{
			if(keypad == 224)      keypad=126;//0 
			else if(keypad == 208) keypad=71; //F
			else if(keypad == 176) keypad=79; //E
			else if(keypad == 112) keypad=61; //d
		}
	}
    return keypad;
}

void display_output(int num)
{
	int mask = 0xFFFF80FF;
	int temp = num << 8; //shift by 8 bits to left to update display bits in x30[14:8]
	asm volatile( 
	    "and x30, x30, %1\n\t"
	    "or  x30, x30, %0\n\t"
	    :
	    :"r"(temp),"r"(mask)
	    :"x30"
	    );
}

int read_delay(void)
{
	int delay;// read delay signal generated by external circuit(555 timer)
	asm volatile(
		"srli x10, x30, 31\n\t"
		"andi %0, x10, 1\n\t"
        :"=r"(delay)
        :
        :"x10"
        );
    return delay;
}
